blank_issues_enabled: false
contact_links:
  - name: Link to Gist
    url: https://gist.github.com/
    about: Preferred
  - name: Link to Pastebin
    url: https://pastebin.com/
    about: Alternative to Gist
