name: Bug Report (WIP)
description: If you have a reproducible in-game issue.
title: "[Minecraft-Version][BUG] <title>"
labels: Bug
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - label: Yes, i have searched for already existing issues.
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the most recent version of X?
      description: "Please check to see if any newer version fixes the issue you're experiencing."
      options:
        - label: Yes, i am using the most recent version.
          required: true
        - label: Yes, it still happens in the most recent version.
          required: true
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: |
        Select the Minecraft version.
        
        *If your version does not show up here, support for it has been closed.*
      options: [1.16.5, 1.18.1]
    validations:
      required: true
  - type: input
    attributes:
      label: Forge Version
      description: |
        The Forge version you are using.
        
        Saying "latest" is not valid.
      placeholder: "xx.xx.xx"
    validations:
      required: true
  - type: input
    attributes:
      label: Immersive Engineering Version
      description: |
        The Immersive Engineering version you are using.
        
        Saying "latest" is not valid.
      placeholder: "xx.xx.xx-xxx"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        Images say more than a thousand words, so if you are bad at explaining things like me, throw in some images to accompany the `What happend?` section above.  
        (Perhaps you could even reference them in that section too)
      placeholder: |
        1. One
        2. Two
        3. Three
    validations:
      required: false
