name: Report A
description: Hopefully this works.
title: "X did Y and thats not what Z should do."
body:
  - type: markdown
    attributes:
      value: |
        ## Markdown
        Markdown Example
  - type: checkboxes
    attributes:
      label: Checkboxes
      description: These are Checkboxes.
      options:
        - label: Required.
          required: true
        - label: Optional.
          required: false
  - type: dropdown
    attributes:
      label: Dropdown
      description: This is a Dropdown menu with a few options to choose from.
      options: [1.0, 1.1, 1.2, 1.3]
    validations:
      required: true
  - type: input
    attributes:
      label: Input
      description: This is a single-line text input field.
      placeholder: ABC-123
    validations:
      required: true
  - type: textarea
    attributes:
      label: TextArea
      description: This is a multi-line text input field.
      placeholder: |
        Line 1
        Line 2
        Line 3
        Line N
    validations:
      required: true
