name: Report A
description: Hopefully this works.
title: "X did Y and thats not what Z should do."
body:
  - type: checkboxes
    attributes:
      label: Checkbox
      description: This is a Checkbox.
      options:
        - label: Yes.
          required: true
  - type: dropdown
    attributes:
      label: Dropdown
      description: This is a Dropdown.
      options: [1.16.5, 1.18.1, 1.18.2]
    validations:
      required: true
  - type: input
    attributes:
      label: Input
      description: This is an Input.
      placeholder: ABC-123
    validations:
      required: true
  - type: textarea
    attributes:
      label: TextArea
      description: This is an TextArea
      placeholder: |
        1. One
        2. Two
        3. Three
    validations:
      required: true
